Feature/mobile menu
ahmetbozaci/training-mobile-menu pull request #1
Opened 2021-06-27 20:03 UTC by ahmetbozaci

I add simple function for open menu in mobile version.

2021-06-27 22:15 UTC, george-swift commented
## Invalid Pull Request ❌ 

Hello Ahmet,

Before this project can be reviewed, kindly ensure that there are no linter errors. I'm sure you must have put in a lot of work but passing linters is a general requirement before any review. After fixing them, you can go ahead and ask for a code review.
You should get a review following a valid request in less than 12 hrs. Godspeed!

<img src="https://media.giphy.com/media/gjlS47uyNz1W0L2v1L/giphy.gif"/>

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-27 22:19 UTC, george-swift requested changes
## Invalid Pull Request ❌ 

Hello Ahmet,

Before this project can be reviewed, kindly ensure that there are no linter errors. I'm sure you must have put in a lot of work but passing linters is a general requirement before any review. After fixing them, you can go ahead and ask for a code review.
You should get a review following a valid request in less than 12 hrs. Godspeed!

<img src="https://media.giphy.com/media/gjlS47uyNz1W0L2v1L/giphy.gif"/>


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-28 15:13 UTC, Berabjesus requested changes
# Status: CHANGES REQUIRED :warning: :construction: 
Hey @ahmetbozaci great job working on the previous review 👏 👏 
### You have a few changes to carry out before we proceed so please take a look at the things you have to work on and their respective review comments below.

## Required Changes ♻️

- [ ] When a user click (or tap) the hamburger button, the mobile menu should appear. (check inline comment below for further information).

----------
#### **Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**
----------
#### As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
----------
#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-06-28 15:13 UTC, Berabjesus commented on index.html
>        <nav id="desktop-nav">
- [ ] When a user click (or tap) the hamburger button, the mobile menu should appear. Currently, it is just moving the hamburger button to the left.
![image](https://user-images.githubusercontent.com/64360974/123660212-211b3280-d83c-11eb-9667-2cb67750f55a.png)

- Kindy work on this and it's best if you check other functionalities are met. For example: - When a user clicks on the buttons inside the menu, the menu should disappear and also make sure the styling matches the one specified on [figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471).

2021-07-03 13:11 UTC, closed without merging

2021-07-11 22:18 UTC, ccobasi reviewed
Hi [@ahmetbozaci](https://github.com/ahmetbozaci), 

Good job so far! You have a good mastery of git-flow.
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  It is required that you make your readme file look professional. See Microverse [readme template](https://github.com/microverseinc/readme-template).

_Check the comments under the review._

## Optional suggestions
[OPTIONAL] 

- In desktop, when the user scrolls you need to check if the user scrolled to a new section. If so, you should highlight the name of the section in the menu by manipulating the DOM using CSS classes.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-11 22:18 UTC, ccobasi commented on script.js
> +}
- [ ] I see you are trying to implement openMenu function. But it seems something is not right. When I clicked the hamburger menu it does not display the mobile menu. I suggest you see [DOM manipulation](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents) documentation. That will help you to implement the necessary requirements.
- [ ] I also suggest you read the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md).